modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="powertool"
version="${file.jarVersion}"
displayName="PowerTool"
logoFile="powertool.png"
credits=""
authors="Nierhain"
description='''
A powerful tool for a powerful purpose
'''